route:
  enabled: true
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

issuerKey:
  kty: "OKP"
  d: "FoJjD3Q6Wh0JHt-tuN3bwGHmPSWa7p8pVe9P9cDIzWw"
  use: "sig"
  crv: "Ed25519"
  kid: "z6MkvdQnXeKgRceAhNsZYjpQjSFcmTXshyGDvnNw7gziQhjG"
  x: "8FSufgpQ8VXgxnR5svvi-j8_4iXxB0TIsVVb0EiRP7s"
  alg: "EdDSA"

realm:
  id: bae
  displayName: "Keycloak Marketplace"
  displayNameHtml: "<div class=\"kc-logo-text\"><span>Keycloak Marketplace</span></div>"
  did: "did:key:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr"
  user:
    - username: marketplace
      email: marketplace@mymail.com
      password: marketplace
      roles: |
        "CREATE_ISSUER"
  frontend:
    url: https://keycloak-i4t-marketplace-main.apps.fiware.fiware.dev
  orionPep:
    baseUrl: https://orion-ld
    adminUrl: https://orion-ld
    redirectUris:
      - https://orion-ld/
    webOrigins:
      - https://orion-ld/

keycloak:
  image:
    registry: quay.io
    repository: i4trust/keycloak
    tag: 20.0.3-debian-11-r9
  
  service:
    type: ClusterIP
  logging:
    level: INFO
  replicaCount: 1
  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin
  serviceAccount:
    create: true
  rbac:
    create: true
    rules:
      - apiGroups:
        - security.openshift.io
        resourceNames:
        - anyuid
        resources:
        - securitycontextconstraints
        verbs:
        - use

  
  keycloakConfigCli:
    enabled: true
    # current image does not contain 20.0.3., thus we need this fix
    command: 
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.1.jar

    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    existingConfigmap: keycloak-bae-realm
  
  extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_LOG_LEVEL
    value: INFO
  - name: VCISSUER_ISSUER_DID
    value: "did:key:z6MkvdQnXeKgRceAhNsZYjpQjSFcmTXshyGDvnNw7gziQhjG"
  - name: VCISSUER_WALTID_ADDRESS
    value: "http://waltid-vcwaltid"
  - name: VCISSUER_ISSUER_KEY_FILE
    value: /opt/keys/keyfile.json


  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
    - name: providers
      mountPath: /opt/bitnami/keycloak/providers/
    - name: issuer-key
      mountPath: /opt/keys

  extraVolumes:
    - name: profiles
      configMap:
        name: keycloak-bae-profile
    - name: issuer-key
      configMap:
        name: keycloak-bae-key
    - name: providers
      emptyDir: {}
    
  initContainers:
    - name: add-vc-issuer
      image: quay.io/fiware/keycloak-vc-issuer:0.3.4
      imagePullPolicy: Always
      volumeMounts:
        - name: providers
          mountPath: /target
  
  postgresql:
    enabled: false

  externalDatabase:
    host: postgresql
    user: postgres
    database: i4t_marketplace_kc
    password: dbRootPassword
