kind: ConfigMap
apiVersion: v1
metadata:
  name: marketplace-load-plugins-cm
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
data:
  load.sh: |-

    echo "Login to OC cluster"
    oc login $OPENSHIFT_SERVER --token="${OPENSHIFT_TOKEN}"

    echo "Target namespace:" $TARGET_NAMESPACE

    echo "Get ChargingBackend pod"
    POD_NAME=`kubectl -n $TARGET_NAMESPACE get pod -l component=biz-ecosystem-charging-backend -o jsonpath='{.items[0].metadata.name}'`
    echo $POD_NAME

    echo "Loading plugins..."
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- wget -P /opt/business-ecosystem-charging-backend/src/plugins https://github.com/i4Trust/bae-i4trust-service/releases/download/4.0.0/bae-i4trust-service_4.1.0.zip
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- wget -P /opt/business-ecosystem-charging-backend/src/plugins https://github.com/i4Trust/bae-i4trust-service/releases/download/4.0.0/bae-vc-service_4.1.0.zip
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- wget -P /opt/business-ecosystem-charging-backend/src/plugins https://github.com/i4Trust/bae-i4trust-service/releases/download/4.0.0/bae-vc-trusted-issuer-service_4.1.0.zip
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- ./manage.py loadplugin plugins/bae-i4trust-service_4.1.0.zip
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- ./manage.py loadplugin plugins/bae-vc-service_4.1.0.zip
    kubectl -n $TARGET_NAMESPACE exec -i $POD_NAME -c business-api-ecosystem-biz-ecosystem-charging-backend -- ./manage.py loadplugin plugins/bae-vc-trusted-issuer-service_4.1.0.zip
    
