{{- if or .Values.initData.createOfferings.standardI4Trust.basicEnabled .Values.initData.createOfferings.standardI4Trust.premiumEnabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: mp-offering-i4t-std-create-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
spec:
  containers:
    - name: mp-offering-i4t-std-create
      image: python:3
      command:
        - /bin/sh
        - /scripts/entrypoint.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
  volumes:
    - name: scripts
      configMap:
        name: mp-create-offering-i4t-std-cm
  restartPolicy: Never

{{- end }}
