{{- if .Values.lpSpecificRoute.routeEnabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: marketplace-lp-route
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ .Values.lpSpecificRoute.secretName }}
spec:
  host: {{ .Values.lpSpecificRoute.host }}
  to:
    kind: Service
    name: {{ .Values.lpSpecificRoute.serviceName }}
  {{- if .Values.lpSpecificRoute.tls }}
  tls:
  {{- with .Values.lpSpecificRoute.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
