keyrock:
  # Values for fiware/keyrock Helm Chart
  #
  # Chart values file:
  # ref: https://github.com/FIWARE/helm-charts/blob/main/charts/keyrock/values.yaml
  #
  # Deployment on FIWARE OpenShift Cluster
  #   *.apps.fiware.fiware.dev
  #

  #existingSecret: keyrock-secret
  #extraEnvVarsSecret: keyrock-env-secret
  
  ## deployment specific configuration
  statefulset:
    ## configuration of the image to be used
    image:
      ## keyrock image name
      ## ref: https://hub.docker.com/r/fiware/idm
      repository: quay.io/fiware/idm
      ## tag of the image to be used
      tag: 8.1.0
      ## specification of the image pull policy
      #pullPolicy: Always
      pullPolicy: IfNotPresent
    startupProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      failureThreshold: 10

  ## openshift specific route definition. Will not work on plain k8s
  route:
    ## -- should the deployment create openshift routes
    enabled: true
    # -- Routes that should be created
    routes:
      - # -- tls configuration for the route
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
  
  ## ingress configuration
  ingress:
    ## should there be an ingress to connect keyrock with the public internet
    enabled: false
  
  # -- host where keyrock is available at
  #host: https://idp.i4trust-marketplace.fiware.dev

  ## database configuration for keyrock
  db:
    ## host of the database to be used
    host: mysql
    ## user for connecting the database
    user: root
    ## password for connecting the database
    password: dbPassword

  ## admin configuration for accessing keyrock
  admin:
    ## username of the initial keyrock admin
    user: admin
    ## password of the initial admin
    password: admin
    ## email address of the admin user
    email: admin@test.com

  ## Init script for Keyrock DB
  initScript:
    ## -- Enable init script
    initEnabled: true
    ## -- Database name for init script
    dbName: idm
    
  ## Certificates configuration
  certs:
    ## -- Algorithm to firm ID tokens for OIDC
    oidcJwtAlgorithm: RS256
    ## Configuration for PVC mounted at certs/ directory for persistance of HTTPS and application certificates/keys
    pvc:
      ## -- Create PVC mounted at certs/ directory for persistance of HTTPS and application certificates/keys
      enabled: false
      ## -- Size of the PVC for certs/ directory
      size: 2Gi
      
  ## Theme configuration for Keyrock
  theme:
    ## -- Enable theme
      enabled: false

  ## a list of additional env vars to be set, check the keyrock docu for all available options
  ## ref: https://fiware-idm.readthedocs.io/en/latest/installation_and_administration_guide/environment_variables/index.html
  additionalEnvVars:
    - name: IDM_TITLE
      value: i4Trust Marketplace IDP (Demonstrator)
    - name: IDM_DEBUG
      value: "true"
    - name: DEBUG
      value: "*"
    - name: IDM_DB_NAME
      value: idm
    - name: IDM_DB_SEED
      value: "true"
    - name: IDM_EMAIL_HOST
      value: "mailgun-fiware-io.infra.svc.cluster.local"
    - name: IDM_EMAIL_PORT
      value: "25"
    - name: IDM_EMAIL_ADDRESS
      value: "bae-idp@fiware.io"

marketplace:
  id: marketplace-id
  secret: f7e11746-b84f-4748-86e5-107146e888h7
  name: Marketplace
  description: Keyrock client for the marketplace.
  url: http://marketplace.i4trust.fiware.dev
  redirectUrl: http://marketplace.i4trust.fiware.dev/auth/fiware/callback
  grantType: authorization_code,refresh_token
  responseType: code
  tokenTypes: bearer
