apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
data:
  init-db.sh: |
    mongo <<EOF
    var rootUser = 'root';
    var rootPassword = 'dbPassword';
    var admin = db.getSiblingDB('admin');
    admin.auth(rootUser, rootPassword);
    db = db.getSiblingDB('charging_db');
    db.createUser({
        user: 'charging',
        pwd: 'charging',
        roles: [{
            role: 'readWrite',
            db: 'charging_db'
          }]
    });

    db = db.getSiblingDB('belp_db');
    db.createUser({
        user: 'belp',
        pwd: 'belp',
        roles: [{
            role: 'readWrite',
            db: 'belp_db'
          }]
    });

    {{- range $v := .Values.initDb.externalIdp.idp }}
    db.idps.insertOne(
    {
      "name" : {{ $v.name | quote }},
      "idpId" : {{ $v.id | quote }},
      "server" : {{ $v.server | quote }},
      "description" : {{ $v.description | quote }},
      "provider" : "i4trust",
      "clientID" : {{ $.Values.initDb.externalIdp.clientID | quote }},
      "tokenKey" : {{ $.Values.initDb.externalIdp.tokenKey | quote }},
      "tokenCrt" : {{ $.Values.initDb.externalIdp.tokenCrt | quote }},
      "callbackURL" : {{ $v.callbackURL | quote }}
    });
    {{- end }}
    
    
    
    EOF
