mongodb:
  # Values for bitnami/mongodb Helm Chart
  #
  # Chart values file:
  # ref: https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
  #
  # Deployment on FIWARE OpenShift Cluster
  #   *.apps.fiware.fiware.dev
  #

  image:
    ## Bitnami MongoDB registry
    ##
    registry: quay.io
    ## Bitnami MongoDB image name
    ##
    repository: i4trust/mongodb
    ## Bitnami MongoDB image tag
    ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
    ##
    tag: 4.4.13
    ## Specify a imagePullPolicy
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent

  ## MongoDB architecture. Allowed values: standalone or replicaset
  ##
  architecture: standalone

  ## Use StatefulSet instead of Deployment when deploying standalone
  ##
  useStatefulSet: false

  ## MongoDB Authentication parameters
  ##
  auth:
    ## Enable authentication
    ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
    ##
    enabled: true
    ## MongoDB root password
    ## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
    ##
    rootPassword: dbPassword

  #extraEnvVarsSecret: mongo-users-secret
  #existingSecret: mongo-root-secret

  ## initdb scripts
  initdbScriptsConfigMap: mongodb-cm

  ## Persistence
  persistence:
    enabled: true

  ## MongoDB pods' Security Context.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ##
  podSecurityContext:
    enabled: false

  ## MongoDB containers' Security Context (main and metrics container).
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ##
  containerSecurityContext:
    enabled: false


initDb:
  externalIdp:
    clientID: "EU.EORI.DEMARKETPLACE"
    #tokenKey: "/business-ecosystem-logic-proxy/key.pem"
    tokenKey: "/opt/business-ecosystem-logic-proxy/key.pem"
    #tokenCrt: "/business-ecosystem-logic-proxy/cert.pem"
    tokenCrt: "/opt/business-ecosystem-logic-proxy/cert.pem"
    idp: []
      #- name: "Service Provider"
      #  id: "EU.EORI.DEPROVIDER"
      #  did: "did:key:abcdefghijklmnopqrstuvwxyz"
      #  server: "https://provider-keyrock-0-i4t-mp-main.apps.fiware.fiware.dev"
      #  description: "Employee IDP of Service Provider"
      #  callbackURL: "https://marketplace-biz-ecosystem-logic-proxy-0-i4t-mp-main.apps.fiware.fiware.dev/auth/EU.EORI.DEPROVIDER/callback"
